Repository mir-dataset-loaders/mirdata, pull requests merged in 2023-10, with the labels that each got.

#591 example_metadta.csv -> example_metadata.csv
  docs/source/contributing_examples/example.py
Labels: docs

#555 fix broken link for "OMRAS2 Metadata Project 2009"
  mirdata/datasets/beatles.py
Labels: broken link

#603 Fix setup extras_requirements installation. Add missing comma.
  setup.py
Labels: bug
